{
 "title": "Climbing Madrid",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Sputnik Alcobendas occupation & capacity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sputnik_people", "legendFormat": "Occupation" },
    { "expr": "sputnik_capacity", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Sputnik Las Rozas occupation & capacity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sputnik_lasrozas_people", "legendFormat": "Occupation" },
    { "expr": "sputnik_lasrozas_capacity", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Sharma occupation & capacities",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sharma_occupation", "legendFormat": "Occupation" },
    { "expr": "sharma_soft_cap", "legendFormat": "Soft cap" },
    { "expr": "sharma_hard_cap", "legendFormat": "Hard cap" }
   ]
  }
 ]
}